### ISSUE TITLE
Reactive form validation with mask

### ISSUE THREAD

**Issue by ppyoosuf** [PeterStaev/nativescript-masked-text-field#39] opened 2019-07-05 06:27 UTC
Hi,

I want to validate the value with 10 digit phone number with reactive form .but component returning the value with masked text like (123) 456-1555. my regex on validation is '/^\d{10}'. is there any way to validate this one.

**Comment by PeterStaev** [comment] 2019-07-05 06:54
Duplicate of #20

**Closed as completed by PeterStaev** 2019-07-05 06:54 UTC
Labels: duplicate
